### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by color32342**
This change is [Reviewable](https://reviewable.io/reviews/colororg/helloworld/5)

### CODE REVIEW

**Comment by staycolorful** [comment]
*[`go.mod` line 9 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_aYUfCYUB6Rh2l7U0:-N9_aYUfCYUB6Rh2l7U1:b2f8uy3) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.mod#L9)):*
> ```XML
> 	github.com/gorilla/mux v1.8.0
> 	github.com/julienschmidt/httprouter v1.3.0
> 	github.com/lib/pq v1.10.6 // indirect
> ```

config version

**Comment by staycolorful** [comment]
iwerw

**Comment by staycolorful** [comment]
sdfsf

**Comment by staycolorful** [comment]
:lgtm:

**Comment by color32342** [comment]
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/colororg/helloworld/5#-N9_eJwL53vXfC76Whfk):*
可以合并版本

**Comment by color32342** [comment]
*[`go.mod` line 9 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_aYUfCYUB6Rh2l7U0:-N9_eeif-HJxDv46GpPc:b2ni9ah) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.mod#L9)):*
<details><summary><i>Previously, staycolorful wrote…</i></summary><blockquote>

config version
</blockquote></details>

ok

**Comment by color32342** [comment]
*[`go.sum` line 116 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_fu5g0ImudTvEcC4n:-N9_fu5g0ImudTvEcC4o:b-og1hrh) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.sum#L116)):*
> ```
> golang.org/x/tools v0.0.0-20190226205152-f727befe758c/go.mod h1:9Yl7xja0Znq3iFh3HoIrodX9oNMXvdceNzlUR8zjMvY=
> golang.org/x/tools v0.0.0-20190311212946-11955173bddd/go.mod h1:LCzVGOaR6xXOjkQ3onu1FJEFr0SW1gC7cKk1uF8kGRs=
> golang.org/x/tools v0.0.0-20190524140312-2c0ae7006135/go.mod h1:RgjU9mgBXZiqYHBnxXauZ1Gv1EHHAz9KjViQ78xBX0Q=
> ```

confirm version

**Comment by staycolorful** [comment]
*[`go.sum` line 116 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_fu5g0ImudTvEcC4n:-N9_gAvO4PDIOoLehqqU:b32wtd) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.sum#L116)):*
<details><summary><i>Previously, color32342 wrote…</i></summary><blockquote>

confirm version
</blockquote></details>

ok

**Review by staycolorful — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_dSCM3Pdn3JpecBi4:bnfp4nl)* status: 0 of 288 files reviewed, 3 unresolved discussions (waiting on @color32342 and @staycolorful)

**Comment by staycolorful** [comment]
*[`go.sum` line 11 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_hH_-E8RYpIYC1sma:-N9_hH_-E8RYpIYC1smb:b-jlmcj6) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.sum#L11)):*
> ```
> github.com/fsnotify/fsnotify v1.4.7/go.mod h1:jwhsz4b93w/PPRr/qN1Yymfu8t87LnFCMoQvtojpjFo=
> github.com/fsnotify/fsnotify v1.4.9/go.mod h1:znqG4EE+3YCdAaPaxE2ZRY/06pZUdp0tY4IgpuI1SZQ=
> github.com/go-pg/pg v8.0.7+incompatible h1:ty/sXL1OZLo+47KK9N8llRcmbA9tZasqbQ/OO4ld53g=
> ```

update

**Review by staycolorful — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_gr101kD53tH04LXb:bnfp4nl)* status: 0 of 288 files reviewed, 4 unresolved discussions (waiting on @color32342 and @staycolorful)

**Comment by staycolorful** [comment]
:lgtm:

**Comment by staycolorful** [comment]
*[`go.sum` line 26 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_idu94AGUgIoM1ubq:-N9_idu94AGUgIoM1ubr:b2ni5mt) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.sum#L26)):*
> ```
> github.com/golang/protobuf v1.4.0/go.mod h1:jodUvKwWbYaEsadDk5Fwe5c77LiNKVO9IDvqG2KuDX0=
> github.com/golang/protobuf v1.4.1/go.mod h1:U8fpvMrcmy5pZrNK1lt4xCsGvpyWQ/VVv6QDs8UjoX8=
> github.com/golang/protobuf v1.4.2/go.mod h1:oDoupMAO8OvCJWAcko0GGGIgR6R6ocIYbsSw735rRwI=
> ```

jjj

**Review by staycolorful — APPROVED** [review]
:lgtm:

> Reviewed 1 of 287 files at r1.
> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_hX76C5np5uVCX9eY:bnfp4nl)* status: 1 of 288 files reviewed, 4 unresolved discussions (waiting on @color32342 and @staycolorful)

**Comment by staycolorful** [comment]
*[`-- commits` line 8 at r5](https://reviewable.io/reviews/colororg/helloworld/5#-N9_eJwL53vXfC76Whfk):*
<details><summary><i>Previously, color32342 wrote…</i></summary><blockquote>

可以合并版本
</blockquote></details>

ok

**Review by staycolorful — COMMENTED** [review]
> Reviewed 286 of 287 files at r1.
> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5)* status: 18 of 288 files reviewed, 4 unresolved discussions (waiting on @color32342 and @staycolorful)

**Review by staycolorful — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5)* status: 22 of 288 files reviewed, 3 unresolved discussions (waiting on @color32342 and @staycolorful)

**Comment by staycolorful** [comment]
*[`go.sum` line 26 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_idu94AGUgIoM1ubq:-N9_k1hjDAxCBJZsNdf5:b32wvb) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.sum#L26)):*
<details><summary><i>Previously, staycolorful wrote…</i></summary><blockquote>

jjj
</blockquote></details>

qs

**Comment by staycolorful** [comment]
*[`go.sum` line 115 at r3](https://reviewable.io/reviews/colororg/helloworld/5#-N9_kenxAijAVfu4mrMN:-N9_keny3GwDWmYoCKn5:b32vad) ([raw file](https://github.com/colororg/helloworld/blob/bfe683969bbd95337b2356eabca06209991ebec8/go.sum#L115)):*
> ```
> golang.org/x/tools v0.0.0-20190114222345-bf090417da8b/go.mod h1:n7NCudcB/nEzxVGmLbDWY5pfWTLqBcC2KZ6jyYvM4mQ=
> golang.org/x/tools v0.0.0-20190226205152-f727befe758c/go.mod h1:9Yl7xja0Znq3iFh3HoIrodX9oNMXvdceNzlUR8zjMvY=
> golang.org/x/tools v0.0.0-20190311212946-11955173bddd/go.mod h1:LCzVGOaR6xXOjkQ3onu1FJEFr0SW1gC7cKk1uF8kGRs=
> ```

11

**Review by color32342 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 287 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_e-GrEnHYMiMu-hBV:bnfp4nl)* status: 22 of 288 files reviewed, 2 unresolved discussions (waiting on @color32342 and @staycolorful)

___
*[`go.sum` line 115 at r3](https://reviewable.io/reviews/colororg/helloworld/5#-N9_kenxAijAVfu4mrMN:-N9_l4zTCglGccOyJKSb:b3kr0) ([raw file](https://github.com/colororg/helloworld/blob/bfe683969bbd95337b2356eabca06209991ebec8/go.sum#L115)):*
<details><summary><i>Previously, staycolorful wrote…</i></summary><blockquote>

11
</blockquote></details>

1

**Review by color32342 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5)* status: 22 of 288 files reviewed, 2 unresolved discussions (waiting on @color32342 and @staycolorful)

___
*[`go.sum` line 26 at r1](https://reviewable.io/reviews/colororg/helloworld/5#-N9_idu94AGUgIoM1ubq:-N9_lNlZ5tMcIXsbmRAn:b-896fix) ([raw file](https://github.com/colororg/helloworld/blob/8505b1bdcbf535d9ccde7e1d200357fb2a88b6ff/go.sum#L26)):*
<details><summary><i>Previously, staycolorful wrote…</i></summary><blockquote>

qs
</blockquote></details>

Done.

**Review by color32342 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_lWJ15BP255hbPaop:bnfp4nl)* status: 22 of 288 files reviewed, 1 unresolved discussion (waiting on @staycolorful)

**Review by color32342 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_ldw12wPDBQ-uUlA4:bnfp4nl)* status: 22 of 288 files reviewed, 1 unresolved discussion (waiting on @staycolorful)

**Review by color32342 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/colororg/helloworld/5#-:-N9_lflFEUkTSUsyJYQw:bnfp4nl)* status: 22 of 288 files reviewed, 1 unresolved discussion (waiting on @staycolorful)

**Pull request closed without merging**
